"""Persistence operations for Project.

Repositories only perform persistence work: no HTTP exceptions, no AI
logic. `create`/`update`/`delete` flush (so autogenerated IDs and
`onupdate` timestamps are available to the caller) but never commit —
committing is a service-layer responsibility.
"""

from typing import Any

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.project import Project


class ProjectRepository:
    def __init__(self, db: Session) -> None:
        self.db = db

    def create(self, data: dict[str, Any]) -> Project:
        project = Project(**data)
        self.db.add(project)
        self.db.flush()
        return project

    def list(self) -> list[Project]:
        stmt = select(Project).order_by(Project.id)
        return list(self.db.execute(stmt).scalars())

    def get_by_id(self, project_id: int) -> Project | None:
        return self.db.get(Project, project_id)

    def update(self, project: Project, data: dict[str, Any]) -> Project:
        for key, value in data.items():
            setattr(project, key, value)
        self.db.flush()
        return project

    def delete(self, project: Project) -> None:
        self.db.delete(project)
        self.db.flush()
